[tool.poetry]
name = "bookingpiano"
version = "0.1.0"
description = ""
authors = ["demo"]
readme = "README.md"
packages = [{include = "bookingpiano"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"