# Generated by Django 4.2.7 on 2024-02-11 14:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField(max_length=1000)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="placeholder",
                        max_length=255,
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
    ]
